# Generated by Django 5.2.17 on 2026-10-05 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_shop_cancellation_reason_shop_cancelled_at_and_more'),
        ('sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['shop', '-created_at'], name='sync_logs_shop_id_d11caf_idx'),
        ),
    ]
