# Generated by Django 5.2.17 on 2026-09-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', "Période d'essai"), ('ACTIVE', 'Actif'), ('GRACE_PERIOD', 'Période de grâce'), ('EXPIRED', 'Expiré')], default='TRIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='subscription_plan',
            field=models.CharField(choices=[('TRIAL', 'Essai gratuit'), ('ESSENTIEL', 'Essentiel'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], default='TRIAL', max_length=20),
        ),
    ]
