# Generated by Django 5.2.17 on 2026-09-24 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shop_last_payment_date_shop_subscription_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('payment_code', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Code de paiement')),
                ('plan', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV_MONEY', 'Moov Money')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PENDING_REVIEW', 'En attente de validation'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('duration_days', models.IntegerField(default=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.shop')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', '-created_at'], name='payments_shop_id_33fae6_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['payment_code'], name='payments_payment_98b3bf_idx')],
            },
        ),
    ]
