# Generated by Django 5.2.17 on 2026-09-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shop_last_payment_date_shop_subscription_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('plan', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV_MONEY', 'Moov Money'), ('CASH', 'Espèces'), ('OTHER', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Confirmé'), ('CANCELLED', 'Annulé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('duration_days', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.shop')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', '-created_at'], name='payments_shop_id_33fae6_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx')],
            },
        ),
    ]
