# Generated by Django 5.2.17 on 2026-09-24 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_transac_a1f824_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid_at',
            new_name='approved_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='error_message',
            new_name='rejection_reason',
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_code',
            field=models.CharField(db_index=True, default='MB-TEMP-0000-0000', editable=False, max_length=20, unique=True, verbose_name='Code de paiement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ORANGE_MONEY', 'Orange Money'), ('WAVE', 'Wave'), ('MOOV_MONEY', 'Moov Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PENDING_REVIEW', 'En attente de validation'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_code'], name='payments_payment_98b3bf_idx'),
        ),
    ]
