# Generated by Django 5.2.17 on 2026-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name="Raison de l'annulation"),
        ),
        migrations.AddField(
            model_name='shop',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AlterField(
            model_name='shop',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('ESSENTIEL', 'Essentiel'), ('PRO', 'Pro'), ('BUSINESS', 'Business')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shop',
            name='subscription_status',
            field=models.CharField(choices=[('PENDING_VALIDATION', 'En attente de validation'), ('TRIAL', "Période d'essai"), ('ACTIVE', 'Actif'), ('GRACE_PERIOD', 'Période de grâce'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='PENDING_VALIDATION', max_length=20),
        ),
    ]
